[package]
name = "simple-tracing-kafka-appender"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.37.0" ,features = ["cmake-build"]}
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json"] }